spring:
  datasource:
      dynamic:
        datasource:
          trader:
            url: jdbc:sqlserver://10.101.10.21;DatabaseName=TradeOrder11
            username: sa
            password: rg@ziguang888
            driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          tradeFlow:
            url: jdbc:mysql://127.0.0.1/tradeFlow?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
            username: root
            password: ziguang@888
            driver-class-name: com.mysql.jdbc.Driver
        primary: trader
  servlet:
    multipart:
      max-file-size: 10MB
      location: /tmp
server:
  tomcat:
    basedir: /tmp/tomcat
  port: 9999
  servlet:
    context-path: /trader

# 配置slq打印日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#server:
#  port: 443
#  ssl:
#    key-store: classpath:server.jks
#    key-store-password: sg7x0wr2fb3yc
#    key-store-type: JKS
#logging:
#  level:
#    com.*: debug

