spring:
  datasource:
    url: jdbc:sqlserver://52.82.105.72;DatabaseName=TradeOrder11
    username: sa
    password: 4UHsIEHBinA9puEu
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  servlet:
    multipart:
      max-file-size: 10MB
      location: /tmp
server:
  tomcat:
    basedir: /tmp/tomcat
  port: 9999
  servlet:
    context-path: /trader

# 配置slq打印日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#server:
#  port: 443
#  ssl:
#    key-store: classpath:server.jks
#    key-store-password: sg7x0wr2fb3yc
#    key-store-type: JKS
#logging:
#  level:
#    com.*: debug

